version: "3"

services:
  mariadb:
    image: mariadb:10.6.8
    container_name: maria_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - 3306:3306  
    restart: always
  mongodb:
    image: mongo:4.2.21
    container_name: mongo_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=mydb
    ports:
      - 27017:27017
    restart: always

      